name: Linux

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main" ]

env:
  UBSAN_OPTIONS: print_stacktrace=1:halt_on_error=1

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 4

    steps:
    - uses: actions/checkout@v4
    - name: clang-format
      run: ./SC.sh format check
    - name: install
      run: sudo apt install -y liburing-dev
    - name: configure
      run: ./SC.sh build configure
    - name: build
      run: ./SC.sh build compile
    - name: test
      run: ./SC.sh build run
    # - name: install gdb
    #   run: sudo apt install -y gdb
    # - name: test in gdb
    #   run: gdb --batch -ex "run" -ex "quit" --args _Build/_Outputs/linux-x86_64-make-gcc-Debug/SCTest
