name: macOS x64

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main" ]

env:
  UBSAN_OPTIONS: print_stacktrace=1:halt_on_error=1

jobs:
  build:

    runs-on: macos-latest
    timeout-minutes: 4

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./SC.sh build configure
    - name: compile
      run: ./SC.sh build compile
    - name: test
      run: _Build/_Outputs/macOS-13.0-arm64\ x86_64-XCode-clang-15-Debug/SCTest
      # run: lldb -o "run" -o "quit" -- _Build/_Outputs/macOS-13.0-arm64\ x86_64-XCode-clang-15-Debug/SCTest