name: macOS x64

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main" ]

env:
  UBSAN_OPTIONS: print_stacktrace=1:halt_on_error=1

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./SCBuild.sh
    - name: build
      run: make -j -C _Build/Projects/Make
    - name: test
      run: _Build/Output/Posix-Any-Any-Makefile-Debug/SCTest
