name: Windows

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 4

    steps:
    - uses: actions/checkout@v4
    - name: configure
      shell: cmd
      run: SC.bat build configure
    - name: compile
      shell: cmd
      run: SC.bat build compile
    - name: test
      shell: cmd
      run: SC.bat build run