name: Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        config: [ Debug, Release ]
        params: [ { os: windows-2022, generator: vs2022 },
                  { os: windows-2019, generator: vs2019 } ]
    runs-on: ${{ matrix.params.os }}
    timeout-minutes: 8

    steps:
    - uses: actions/checkout@v4
    - name: configure
      shell: cmd
      run: SC.bat build configure SCTest ${{ matrix.config }} ${{ matrix.params.generator }}
    - name: compile
      shell: cmd
      run: SC.bat build compile SCTest ${{ matrix.config }} ${{ matrix.params.generator }}
    - name: test
      shell: cmd
      run: SC.bat build run SCTest ${{ matrix.config }} ${{ matrix.params.generator }}